#!/bin/bash
#

T=/tmp/$$.txt
echo "Test PyTechBrain " > ${T}
echo "        ------- " >> ${T}
sudo ./ftx_prog --dump | grep "Product =" >> ${T}
echo "        --[teraz zapis]----- " >> ${T}
sudo ./ftx_prog --product ABIX_PyTechBrain > /dev/null
echo "        ------- " >> ${T}
sudo ./ftx_prog --dump | grep "Product =" >> ${T}

cat ${T}
rm ${T}
