#!/bin/bash
#
# required:
# apt install build-essential gcc make libftdi-dev
#

# writing FirmataPlus to Arduino
./avrdude -Cavrdude.conf -v -patmega328p -carduino -P/dev/ttyUSB0 -b115200 -D -Uflash:w:FirmataPlus.ino.hex:i

# writing product_name to FTDI
echo "Test PyTechBrain " 
echo "        ------- "
sudo ./ftx_prog --dump | grep "Product =" 
echo "        --[teraz zapis]----- " 
sudo ./ftx_prog --product ABIX_PyTechBrain 
echo "        ------- " 
sudo ./ftx_prog --dump | grep "Product ="


